"""Tools for the AI Sales Agent.

These functions are passed to the Gemini SDK. The SDK uses the type hints
and docstrings to automatically generate the function calling schema.
"""
import hashlib
from typing import Optional

from app.db import SessionLocal
from app.services.search_service import hybrid_search, get_product_by_sku
from app.services.reranker import rerank
from app.llm import embed, generate_ecommerce_description

async def search_products(
    query: str, 
    category: str | None = None, 
    min_price: float | None = None, 
    max_price: float | None = None
) -> str:
    """Search engine. Finds the most suitable products from the database based on the customer's query.
    
    Args:
        query: The customer's search query (e.g., 'winter black leather boots').
        category: Optional. The category of the searched product (e.g., 'Shoes').
        min_price: Optional. Minimum price filter.
        max_price: Optional. Maximum price filter.
        
    Returns:
        List of found products (includes title, price, rating, sku, and description snippets).
    """
    try:
        query_vectors = await embed([query])
        query_vector = query_vectors[0]
        
        async with SessionLocal() as session:
            candidates = await hybrid_search(
                query=query,
                query_embedding=query_vector,
                limit=10,
                category=category,
                min_price=min_price,
                max_price=max_price,
                session=session
            )
            
        if not candidates:
            return "No products found. Please try searching with different criteria."
            
        reranked = await rerank(query=query, candidates=candidates, top_k=3)
        
        results = []
        for chunk, product, score in reranked:
            res = (
                f"SKU: {product.sku}\n"
                f"Title: {product.title}\n"
                f"Price: ${product.price_usd}\n"
                f"Rating: {product.avg_rating}/5\n"
                f"Description snippet: {chunk.content}\n"
            )
            results.append(res)
            
        return "\n---\n".join(results)
    except Exception as e:
        return f"An error occurred during the search: {str(e)}"

async def get_product_details(sku: str) -> str:
    """Retrieves all details of a specific product given its SKU.
    
    Args:
        sku: The unique stock keeping unit code of the product (e.g., 'B01M...').
        
    Returns:
        Detailed information about the product.
    """
    try:
        product = await get_product_by_sku(sku)
        if not product:
            return f"Product with SKU: {sku} could not be found."
            
        return (
            f"Title: {product.title}\n"
            f"Category: {product.category}\n"
            f"Price: ${product.price_usd}\n"
            f"Rating: {product.avg_rating}/5\n"
        )
    except Exception as e:
        return f"An error occurred while fetching details: {str(e)}"

async def check_stock(sku: str) -> str:
    """Checks the current warehouse stock status for the given SKU.
    
    Args:
        sku: The unique stock keeping unit code of the product.
        
    Returns:
        Stock quantity or out of stock information.
    """
    # Mock implementation: Generate deterministic pseudo-random stock based on SKU string hash
    hash_val = int(hashlib.md5(sku.encode()).hexdigest(), 16)
    stock = hash_val % 15 # 0 ile 14 arası stok
    
    if stock == 0:
        return f"Unfortunately, product {sku} is currently out of stock."
    elif stock < 3:
        return f"Hurry! Only {stock} units left in stock for product {sku}."
    return f"Product {sku} is in stock (Current stock: {stock} units)."

async def generate_marketing_description(title: str, features: str) -> str:
    """Generates an engaging, marketing-oriented rich description text for a product.
    
    Args:
        title: The title of the product.
        features: The key features of the product (briefly).
        
    Returns:
        Rich marketing description generated by AI.
    """
    try:
        prompt = f"Title: {title}\nFeatures: {features}"
        # generate_ecommerce_description returns a 5-tuple: (text, in_tok, out_tok, model, key)
        text, _, _, _, _ = await generate_ecommerce_description(prompt)
        return text
    except Exception as e:
        return f"An error occurred while generating the description: {str(e)}"
